"""add job_url to manual_job_postings and manual_job_posting_id to application_tracker_entries

Revision ID: 03f7ad2cd8e7
Revises: 8f97c9870fd9
Create Date: 2026-06-14 23:07:57.495628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f7ad2cd8e7'
down_revision: Union[str, Sequence[str], None] = '8f97c9870fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_tracker_entries', sa.Column('manual_job_posting_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_application_tracker_entries_manual_job_posting_id'), 'application_tracker_entries', ['manual_job_posting_id'], unique=False)
    op.create_foreign_key(None, 'application_tracker_entries', 'manual_job_postings', ['manual_job_posting_id'], ['id'], ondelete='SET NULL')
    op.add_column('manual_job_postings', sa.Column('job_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_job_postings', 'job_url')
    op.drop_constraint(None, 'application_tracker_entries', type_='foreignkey')
    op.drop_index(op.f('ix_application_tracker_entries_manual_job_posting_id'), table_name='application_tracker_entries')
    op.drop_column('application_tracker_entries', 'manual_job_posting_id')
    # ### end Alembic commands ###
