"""add profile_information table

Revision ID: 178cc82e23d3
Revises: 6a1df5687881
Create Date: 2026-05-25 15:31:37.621258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178cc82e23d3'
down_revision: Union[str, Sequence[str], None] = '6a1df5687881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('seniority_level', sa.String(length=100), nullable=True),
    sa.Column('leadership_experience', sa.Text(), nullable=True),
    sa.Column('salary_expectation', sa.String(length=255), nullable=True),
    sa.Column('work_model', sa.String(length=100), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('employment_types', sa.JSON(), nullable=True),
    sa.Column('work_experience', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('courses', sa.JSON(), nullable=True),
    sa.Column('volunteering', sa.JSON(), nullable=True),
    sa.Column('soft_skills', sa.JSON(), nullable=True),
    sa.Column('hard_skills', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('publications', sa.JSON(), nullable=True),
    sa.Column('honors_awards', sa.JSON(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_information')
    # ### end Alembic commands ###
