"""rework cover letter schema add snapshots update profile fields

Revision ID: 1f45652f6313
Revises: fa5fe069369e
Create Date: 2026-05-31 14:48:50.599006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f45652f6313'
down_revision: Union[str, Sequence[str], None] = 'fa5fe069369e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letter_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_letter_id', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revision_type', sa.Enum('INITIAL', 'AI_REVISION', 'USER_REVISION', name='coverletterrevisiontype'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letter_snapshots_cover_letter_id'), 'cover_letter_snapshots', ['cover_letter_id'], unique=False)
    op.add_column('cover_letters', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cover_letters', sa.Column('document_name', sa.String(length=255), nullable=True))
    op.add_column('cover_letters', sa.Column('document_filename', sa.String(length=255), nullable=True))
    op.add_column('cover_letters', sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('cover_letters', sa.Column('layout_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('cover_letters', 'generated_content')
    op.drop_column('cover_letters', 'title')
    op.add_column('profile_information', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('profile_information', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('profile_information', sa.Column('street', sa.String(length=512), nullable=True))
    op.add_column('profile_information', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('profile_information', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_column('profile_information', 'name')
    op.drop_column('profile_information', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_information', sa.Column('address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('profile_information', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('profile_information', 'location')
    op.drop_column('profile_information', 'city')
    op.drop_column('profile_information', 'street')
    op.drop_column('profile_information', 'last_name')
    op.drop_column('profile_information', 'first_name')
    op.add_column('cover_letters', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('cover_letters', sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('cover_letters', 'layout_settings')
    op.drop_column('cover_letters', 'is_saved')
    op.drop_column('cover_letters', 'document_filename')
    op.drop_column('cover_letters', 'document_name')
    op.drop_column('cover_letters', 'content')
    op.drop_index(op.f('ix_cover_letter_snapshots_cover_letter_id'), table_name='cover_letter_snapshots')
    op.drop_table('cover_letter_snapshots')
    # ### end Alembic commands ###
