"""add unique constraint for search profile names

Revision ID: 361bc55a5937
Revises: b8043c162ef4
Create Date: 2026-05-13 13:49:25.597220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361bc55a5937'
down_revision: Union[str, Sequence[str], None] = 'b8043c162ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_profile_name', 'search_profiles', ['user_id', 'profile_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_profile_name', 'search_profiles', type_='unique')
    # ### end Alembic commands ###
