"""add_search_run_snapshots_and_set_search_profile_fk_to_null_on_delete

Revision ID: 40a52200c2ff
Revises: a0ed68e39a26
Create Date: 2026-05-17 11:57:52.055149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a52200c2ff'
down_revision: Union[str, Sequence[str], None] = 'a0ed68e39a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_runs', sa.Column('search_profile_name_snapshot', sa.String(length=255), nullable=False))
    op.add_column('search_runs', sa.Column('query_snapshot', sa.String(length=255), nullable=False))
    op.add_column('search_runs', sa.Column('location_snapshot', sa.String(length=255), nullable=False))
    op.add_column('search_runs', sa.Column('remote_only_snapshot', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('search_runs', sa.Column('employment_types_snapshot', postgresql.ARRAY(sa.String(length=50)), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('search_runs', sa.Column('experience_levels_snapshot', postgresql.ARRAY(sa.String(length=50)), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('search_runs', sa.Column('radius_km_snapshot', sa.Integer(), nullable=True))
    op.alter_column('search_runs', 'search_profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('search_runs_search_profile_id_fkey'), 'search_runs', type_='foreignkey')
    op.create_foreign_key("search_runs_search_profile_id_fkey", 'search_runs', 'search_profiles', ['search_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("search_runs_search_profile_id_fkey", 'search_runs', type_='foreignkey')
    op.create_foreign_key(op.f('search_runs_search_profile_id_fkey'), 'search_runs', 'search_profiles', ['search_profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('search_runs', 'search_profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('search_runs', 'radius_km_snapshot')
    op.drop_column('search_runs', 'experience_levels_snapshot')
    op.drop_column('search_runs', 'employment_types_snapshot')
    op.drop_column('search_runs', 'remote_only_snapshot')
    op.drop_column('search_runs', 'location_snapshot')
    op.drop_column('search_runs', 'query_snapshot')
    op.drop_column('search_runs', 'search_profile_name_snapshot')
    # ### end Alembic commands ###
