"""add_tracker_status_dates_and_remove_job_fk_delete_cascades

Revision ID: 4cd7a33a7b3f
Revises: 40a52200c2ff
Create Date: 2026-05-17 19:31:08.672607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd7a33a7b3f'
down_revision: Union[str, Sequence[str], None] = '40a52200c2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_tracker_entries', sa.Column('interview_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('application_tracker_entries', sa.Column('offer_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('application_tracker_entries', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('application_tracker_entries', sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('application_tracker_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('application_tracker_entries_job_id_fkey'), 'application_tracker_entries', type_='foreignkey')
    op.create_foreign_key('application_tracker_entries_job_id_fkey', 'application_tracker_entries', 'jobs', ['job_id'], ['id'])
    op.drop_constraint(op.f('search_run_jobs_job_id_fkey'), 'search_run_jobs', type_='foreignkey')
    op.create_foreign_key('search_run_jobs_job_id_fkey', 'search_run_jobs', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('search_run_jobs_job_id_fkey', 'search_run_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('search_run_jobs_job_id_fkey'), 'search_run_jobs', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('application_tracker_entries_job_id_fkey', 'application_tracker_entries', type_='foreignkey')
    op.create_foreign_key(op.f('application_tracker_entries_job_id_fkey'), 'application_tracker_entries', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('application_tracker_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('application_tracker_entries', 'withdrawn_at')
    op.drop_column('application_tracker_entries', 'rejected_at')
    op.drop_column('application_tracker_entries', 'offer_at')
    op.drop_column('application_tracker_entries', 'interview_at')
    # ### end Alembic commands ###
