"""alter_users_rename_password_add_columns

Revision ID: 61de0767cd5a
Revises: a80bd5ec14bd
Create Date: 2026-05-07 19:10:40.208501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61de0767cd5a'
down_revision: Union[str, Sequence[str], None] = 'a80bd5ec14bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password', new_column_name='password_hash')
    op.add_column('users', sa.Column('role', sa.String(length=50), server_default='user', nullable=False))
    op.add_column('users', sa.Column('trial_job_searches_left', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'trial_job_searches_left')
    op.drop_column('users', 'role')
    op.alter_column('users', 'password_hash', new_column_name='hashed_password')
    # ### end Alembic commands ###
