"""add cv_reconstruction to profile_information for prompt iteration

Revision ID: 6996e8474a3c
Revises: 178cc82e23d3
Create Date: 2026-05-27 15:38:19.736915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6996e8474a3c'
down_revision: Union[str, Sequence[str], None] = '178cc82e23d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_information', sa.Column('cv_reconstruction', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_information', 'cv_reconstruction')
    # ### end Alembic commands ###
