"""add_markdown_extraction_method

Revision ID: 6a1df5687881
Revises: 40c3e2ebdae9
Create Date: 2026-05-24 16:44:42.705793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1df5687881'
down_revision: Union[str, Sequence[str], None] = '40c3e2ebdae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE extractionmethod ADD VALUE IF NOT EXISTS 'MARKDOWN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
