"""add signature_image to profile_information

Revision ID: 73043a5d9a39
Revises: 1f45652f6313
Create Date: 2026-06-01 17:00:38.885260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73043a5d9a39'
down_revision: Union[str, Sequence[str], None] = '1f45652f6313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_information', sa.Column('signature_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_information', 'signature_image')
    # ### end Alembic commands ###
