"""add profile_updated_at_snapshot to search_runs

Revision ID: 8f97c9870fd9
Revises: c4a2f9d81e37
Create Date: 2026-06-11 13:56:51.154121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f97c9870fd9'
down_revision: Union[str, Sequence[str], None] = 'c4a2f9d81e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cover_letters', 'tone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('search_runs', sa.Column('profile_updated_at_snapshot', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))
    op.drop_constraint(op.f('uq_user_profile_run_date'), 'search_runs', type_='unique')
    op.create_unique_constraint('uq_user_profile_run_date_version', 'search_runs', ['user_id', 'search_profile_id', 'run_date', 'profile_updated_at_snapshot'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_profile_run_date_version', 'search_runs', type_='unique')
    op.create_unique_constraint(op.f('uq_user_profile_run_date'), 'search_runs', ['user_id', 'search_profile_id', 'run_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('search_runs', 'profile_updated_at_snapshot')
    op.alter_column('cover_letters', 'tone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
