"""refactor_search_profile_filters_and_add_can_load_more_to_search_runs

Revision ID: a0ed68e39a26
Revises: 361bc55a5937
Create Date: 2026-05-15 21:56:55.806173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0ed68e39a26'
down_revision: Union[str, Sequence[str], None] = '361bc55a5937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_profiles', sa.Column('remote_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column(
        'search_profiles',
        'employment_type',
        new_column_name='employment_types',
        existing_type=postgresql.ARRAY(sa.String(length=50)),
        existing_server_default=sa.text("'{}'"),
        existing_nullable=False
    )
    op.add_column('search_profiles', sa.Column('experience_levels', postgresql.ARRAY(sa.String(length=50)), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('search_profiles', sa.Column('radius_km', sa.Integer(), nullable=True))
    op.drop_column('search_profiles', 'experience_level')
    op.drop_column('search_profiles', 'work_model')
    op.drop_column('search_profiles', 'industry')
    op.drop_column('search_profiles', 'company')
    op.add_column('search_runs', sa.Column('can_load_more', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_runs', 'can_load_more')
    op.add_column('search_profiles', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column(
        'search_profiles',
        'employment_types',
        new_column_name='employment_type',
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
        existing_server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False
    )
    op.add_column('search_profiles', sa.Column('industry', postgresql.ARRAY(sa.VARCHAR(length=100)), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('search_profiles', sa.Column('work_model', postgresql.ARRAY(sa.VARCHAR(length=50)), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('search_profiles', sa.Column('experience_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('search_profiles', 'radius_km')
    op.drop_column('search_profiles', 'experience_levels')
    op.drop_column('search_profiles', 'remote_only')
    # ### end Alembic commands ###
