"""add search profile and run tables

Revision ID: b8043c162ef4
Revises: 61de0767cd5a
Create Date: 2026-05-13 12:50:03.239375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8043c162ef4'
down_revision: Union[str, Sequence[str], None] = '61de0767cd5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('work_model', postgresql.ARRAY(sa.String(length=50)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('employment_type', postgresql.ARRAY(sa.String(length=50)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('industry', postgresql.ARRAY(sa.String(length=100)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_profiles_user_id'), 'search_profiles', ['user_id'], unique=False)
    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_profile_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('date_posted', sa.String(length=50), nullable=False),
    sa.Column('current_page', sa.Integer(), server_default='5', nullable=False),
    sa.Column('total_jobs_loaded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_new_jobs_loaded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('load_more_requests_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'search_profile_id', 'run_date', name='uq_user_profile_run_date')
    )
    op.create_index(op.f('ix_search_runs_search_profile_id'), 'search_runs', ['search_profile_id'], unique=False)
    op.create_index(op.f('ix_search_runs_user_id'), 'search_runs', ['user_id'], unique=False)
    op.create_table('search_run_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('is_previously_seen', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('result_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_run_id', 'job_id', name='uq_search_run_job')
    )
    op.create_index(op.f('ix_search_run_jobs_job_id'), 'search_run_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_search_run_jobs_search_run_id'), 'search_run_jobs', ['search_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_run_jobs_search_run_id'), table_name='search_run_jobs')
    op.drop_index(op.f('ix_search_run_jobs_job_id'), table_name='search_run_jobs')
    op.drop_table('search_run_jobs')
    op.drop_index(op.f('ix_search_runs_user_id'), table_name='search_runs')
    op.drop_index(op.f('ix_search_runs_search_profile_id'), table_name='search_runs')
    op.drop_table('search_runs')
    op.drop_index(op.f('ix_search_profiles_user_id'), table_name='search_profiles')
    op.drop_table('search_profiles')
    # ### end Alembic commands ###
