"""add cover letter tables

Revision ID: fa5fe069369e
Revises: 6996e8474a3c
Create Date: 2026-05-28 21:18:08.181129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa5fe069369e'
down_revision: Union[str, Sequence[str], None] = '6996e8474a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_job_postings_user_id'), 'manual_job_postings', ['user_id'], unique=False)
    op.create_table('job_normalizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('manual_job_posting_id', sa.Integer(), nullable=True),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manual_job_posting_id'], ['manual_job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_normalizations_job_id'), 'job_normalizations', ['job_id'], unique=False)
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('manual_job_posting_id', sa.Integer(), nullable=True),
    sa.Column('job_normalization_id', sa.Integer(), nullable=True),
    sa.Column('template', sa.Enum('CLASSIC', 'MODERN', 'COMPACT', name='coverlettertemplate'), nullable=False),
    sa.Column('tone', sa.Enum('FORMAL', 'NEUTRAL', 'CASUAL', name='coverlettertone'), nullable=False),
    sa.Column('must_haves', sa.Text(), nullable=True),
    sa.Column('personal_motivation', sa.Text(), nullable=True),
    sa.Column('why_company', sa.Text(), nullable=True),
    sa.Column('added_value', sa.Text(), nullable=True),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='coverlettergenerationstatus'), nullable=False),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_normalization_id'], ['job_normalizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manual_job_posting_id'], ['manual_job_postings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.drop_table('cover_letters')
    op.drop_index(op.f('ix_job_normalizations_job_id'), table_name='job_normalizations')
    op.drop_table('job_normalizations')
    op.drop_index(op.f('ix_manual_job_postings_user_id'), table_name='manual_job_postings')
    op.drop_table('manual_job_postings')
    op.execute("DROP TYPE IF EXISTS coverlettertemplate")
    op.execute("DROP TYPE IF EXISTS coverlettertone")
    op.execute("DROP TYPE IF EXISTS coverlettergenerationstatus")
    # ### end Alembic commands ###
